.\" Manpage for noiseinjekt.
.\" Contact aldrigmej@gmail.com for comments or help.
.TH man 1 "May 2022" "1.1.0" "noiseinjekt man page"
.SH NAME
noiseinjekt \- A simple C++ library that implements dependecy injection. 
.SH SYNOPSIS
noiseinjekt
.SH DESCRIPTION
noiseinjekt is an A simple C++ library that implements dependecy injection. .
.SH OPTIONS
noiseinjekt does not take any arguments.
.SH BUGS
No known bugs.
.SH AUTHOR
Apostolos (aldrigmej@gmail.com)
